export { default as AddIcon } from './AddIcon.vue';
export { default as ChipIcon } from './ChipIcon.vue';
export { default as DeleteIcon } from './DeleteIcon.vue';
export { default as EditIcon } from './EditIcon.vue';
export { default as EmailIcon } from './EmailIcon.vue';
export { default as PersonIcon } from './PersonIcon.vue';
export { default as PhoneIcon } from './PhoneIcon.vue';
export { default as SearchIcon } from './SearchIcon.vue';
export { default as UserIcon } from './UserIcon.vue';
export { default as BackArrow } from './BackArrow.vue'
export { default as Menu } from './Menu.vue'